services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: bpo_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules # <--- ¡Nuevo Volumen Anónimo para tapar node_modules!
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: bpo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bpo_prueba
      MYSQL_USER: bpo_user
      MYSQL_PASSWORD: bpo_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: